### ISSUE TITLE
Creating new file doesn't auto reload

### ISSUE THREAD

**Issue by EquipableMC** [erenkarakal/SkReloader#2]
When you create a new folder then a new file, it does not automatically reload the files in the new folder unless you restart the server.

**Comment by erenkarakal** [comment]
when you create a new file SkReloader doesn't have access to it since its not parsed yet so you must use /sk reload once.
might or might not do something about it later

**Comment by EquipableMC** [comment]
ahh gotcha, thank you!

**Comment by EquipableMC** [comment]
That did not work.
Edit: I had to restart the server to make it register, kinda annoying to be honest
